// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/query.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 不是赋值，是压缩的唯一ID
	Output        string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_api_proto_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_api_proto_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

type QueryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStatusRequest) Reset() {
	*x = QueryStatusRequest{}
	mi := &file_api_proto_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatusRequest) ProtoMessage() {}

func (x *QueryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatusRequest.ProtoReflect.Descriptor instead.
func (*QueryStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryStatusRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

type QueryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStatusResponse) Reset() {
	*x = QueryStatusResponse{}
	mi := &file_api_proto_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatusResponse) ProtoMessage() {}

func (x *QueryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatusResponse.ProtoReflect.Descriptor instead.
func (*QueryStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryStatusResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_api_proto_query_proto protoreflect.FileDescriptor

const file_api_proto_query_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/query.proto\x12\x05query\"&\n" +
	"\fQueryRequest\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\"*\n" +
	"\rQueryResponse\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\"/\n" +
	"\x12QueryStatusRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\"E\n" +
	"\x13QueryStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result2\x91\x01\n" +
	"\fQueryService\x128\n" +
	"\vSubmitQuery\x12\x13.query.QueryRequest\x1a\x14.query.QueryResponse\x12G\n" +
	"\x0eGetQueryStatus\x12\x19.query.QueryStatusRequest\x1a\x1a.query.QueryStatusResponseB\x0fZ\r./internal/pbb\x06proto3"

var (
	file_api_proto_query_proto_rawDescOnce sync.Once
	file_api_proto_query_proto_rawDescData []byte
)

func file_api_proto_query_proto_rawDescGZIP() []byte {
	file_api_proto_query_proto_rawDescOnce.Do(func() {
		file_api_proto_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_query_proto_rawDesc), len(file_api_proto_query_proto_rawDesc)))
	})
	return file_api_proto_query_proto_rawDescData
}

var file_api_proto_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_query_proto_goTypes = []any{
	(*QueryRequest)(nil),        // 0: query.QueryRequest
	(*QueryResponse)(nil),       // 1: query.QueryResponse
	(*QueryStatusRequest)(nil),  // 2: query.QueryStatusRequest
	(*QueryStatusResponse)(nil), // 3: query.QueryStatusResponse
}
var file_api_proto_query_proto_depIdxs = []int32{
	0, // 0: query.QueryService.SubmitQuery:input_type -> query.QueryRequest
	2, // 1: query.QueryService.GetQueryStatus:input_type -> query.QueryStatusRequest
	1, // 2: query.QueryService.SubmitQuery:output_type -> query.QueryResponse
	3, // 3: query.QueryService.GetQueryStatus:output_type -> query.QueryStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_query_proto_init() }
func file_api_proto_query_proto_init() {
	if File_api_proto_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_query_proto_rawDesc), len(file_api_proto_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_query_proto_goTypes,
		DependencyIndexes: file_api_proto_query_proto_depIdxs,
		MessageInfos:      file_api_proto_query_proto_msgTypes,
	}.Build()
	File_api_proto_query_proto = out.File
	file_api_proto_query_proto_goTypes = nil
	file_api_proto_query_proto_depIdxs = nil
}
